### ISSUE TITLE
Variable insert field in conditional logic in DAT PDF Template needs styling

### ISSUE THREAD

**Issue by JessicaFrank** [CCALI/a2jauthor#117]
Inserting a variable to base a conditional insertion of a template on within PDF DAT templates is difficult because the variable picker is overlaid by the evaluator field ('is true' by default). 

![image](https://user-images.githubusercontent.com/7662028/104064866-4bacfc80-51c4-11eb-9377-bc1dd1a723b1.png)

It also allows you to pick a variable, then have the option to pick additional variables. I don't think the code supports multiple variables with 1 condition, so the display shouldn't. It can encourage authors to add additional variables which won't work like they expect.

**Comment by mitch-mitchel** [comment]
similar problem fixed by this PR - will fix issue in Author when a new deps release happens and then installed in author
https://github.com/CCALI/a2jdeps/pull/68
