### ISSUE TITLE
Add Page validation for GOTO Statements

### ISSUE THREAD

**Issue by JessicaFrank** [CCALI/a2jauthor#146]
Author request to add GOTO statement page name validation. This would be similar to how variable names are validated and an error is shown if the var doesn't exist. 

Currently, the only way to know that your GOTO fails for invalid page name is to run the interview in the viewer/preview and get a Page doesn't exist error. 

Similar to https://github.com/CCALI/CAJA/issues/164

**Comment by janebitovi** [comment]
Errors are reported/inserted for bad GOTO statements now once the code ships
![goto-check-advanced-logic](https://user-images.githubusercontent.com/92131113/174085375-db5421ec-3a0f-4378-ae8b-88a87799b24f.gif)

Further, per slack convo, suggestions bar has been added to logic fields that detect when user is typing a goto or var reference:
![advanced-logic](https://user-images.githubusercontent.com/92131113/174085904-05aa7871-7252-46aa-8043-72636788c485.gif)
