### ISSUE TITLE
Large .mp4 file caused upload failure

### ISSUE THREAD

**Issue by mitch-mitchel** [CCALI/a2jauthor#155]
Had an issue where this GI would not upload through the demo interface or the Interview uploader in Author. Saw that here was a 13.4mb .mp4 file in the .zip and changed that to a 480p .mov file that was about 1.6mb in size, re-zipped up the GI and it was able to upload just fine. Not sure why this caused a problem as I feel we've had other larger GIs in the past and they've uploaded fine.

problem file attached:
[2020 An A2J Guided Interview for Testing A2J Author (August 2020).zip](https://github.com/CCALI/a2jauthor/files/6029983/2020.An.A2J.Guided.Interview.for.Testing.A2J.Author.August.2020.zip)

**Comment by tobiasnteireho** [comment]
This uploads fine in hydra viewerdev and production. Is this a local setup issue?

**Comment by mitch-mitchel** [comment]
could very likely be, can we pair @tobiasnteireho to look at my Apache settings and see if it's a limit on my end?
as per slack convo, this fixed it in local dev (specifically `post_max_filesize` was only 8M):
```
try setting
upload_max_filesize = 1024M
post_max_filesize = 1024M
 in php.ini
 ```
