### ISSUE TITLE
Rewire in viewer with debug panel

### ISSUE THREAD

**Issue by mitch-mitchel** [CCALI/a2jauthor#157]
Moving the debug-panel to Viewer to be used for the Advanced Nav Panel but need to change Author to now just pass the state back and forth that it cares about for Preview mode debug panel 
- [x] Edit This target (always opens QDE for current page)
- [x] Resume Edit target (should remember if QDE was open or not and to what page)
- [x] Fill Sample Value (fills any sample values on the current page in Viewer)
warning?)
- [x] should remember state of answers
- [x] should remember list of traceMessages for the debug log
- [x] should remember showDebugPanel state between previews
- [x] should allow clearing of both above
- [x] should auto clear interview/answers, traceMessages, and set showDebugPanel to 'false' on interview tab
- [x] remove traceMessage from a2jdeps as it's used solely in the Viewer now, clean up tests

**Comment by mikemitchel** [comment]
also fix @CCALI/CAJA#1252

**Comment by JessicaFrank** [comment]
Testing hydra with A2J 7.0-2021-03-10debug preview viewer

Found two bugs that may be related

- [ ] Edit This takes you back to question you entered Preview mode from (same behavior as Resume Edit) and not the question you were last on in Preview

- [ ] The question you are taken back to (the one you entered Preview from) has its fields deleted

Getting an Uncaught TypeError in console 
![image](https://user-images.githubusercontent.com/7662028/110816291-d5268c80-8250-11eb-9fe5-6cb49db563ce.png)

Steps to replicate:

1.  Make a new GI
2. add three fields to 1-Question 1
3. Make a new page
4. Set 1-Question 1 destination to that new page
5. Go into preview mode from 1-Question 1
6. Fill in fields in Preview mode for 1-Question 1
7. Hit Save button on 1-Question 1 to go to new page you created in step 3
8. From that new page, hit "Edit This"
9. You'll be taken to 1-Question 1 in Author, check the fields. They are deleted.
