### ISSUE TITLE
CK editor not displaying in All Text tab

### ISSUE THREAD

**Issue by JessicaFrank** [CCALI/a2jauthor#158]
Click into All Text Tab, then try to edit text in a question text field, get the following error in the console and aren't able to actually edit the text there. 

![image](https://user-images.githubusercontent.com/7662028/110036277-68683b00-7d02-11eb-874d-24e32b1dc790.png)

**Comment by mitch-mitchel** [comment]
Is this happening in production? @JessicaFrank

**Comment by JessicaFrank** [comment]
Can't be reproduced by @mikemitchel or @AnubhavDhingra . 

I tested again on production with a new interview and an existing interview. Tried replicating steps that triggered it when I created this ticket and can't reproduce it. So closing this ticket.
