### ISSUE TITLE
URL WCAG icon isn't in consistent spot for MI interview

### ISSUE THREAD

**Issue by JessicaFrank** [CCALI/a2jauthor#169]
Partner reported new icon for hyperlinks isn't consistently placed in their interview text. 

![image](https://user-images.githubusercontent.com/7662028/113589276-c97f7900-95f6-11eb-8a5b-002229f8c1b0.png)

I can't replicate in a new GI or in an existing GI with a hyperlink, but my existing GI only had one. I had to add a new hyperlink to it to replicate the 2 hyperlinks in the partner GI. 

You can see the partner GI issue on the first page of their interview. 
[CDC Eviction Moratorium Declaration.zip](https://github.com/CCALI/a2jauthor/files/6258835/CDC.Eviction.Moratorium.Declaration.zip)

Initially, the icon for hyperlinks wasn't displaying for their second hyperlink, but I had the author delete it and re-link it. Then the icon appeared, but it's in front of the link, instead of after it like expected. 

![image](https://user-images.githubusercontent.com/7662028/113589691-4b6fa200-95f7-11eb-9d43-10c970b618b1.png)

@AnubhavDhingra and @mikemitchel can you please look at the MI interview and see if you can see why their experience is different than expected?

**Comment by ghost** [comment]
@JessicaFrank  Should i look to see if ckeditor underlines links by default. See notes below.

Steps to reproduce the error: 

- Underline the text before making it a link and then preview. 

How to fix the error: 

- Highlight the text, remove the underline style. Attach the link and then underline text, if you want the link text to be underlined. 

Related to CCALI/CAJA#2489 ; CCALI/CAJA#2527

**Comment by JessicaFrank** [comment]
Yes, can you please look into making the experience uniform @AnubhavDhingra? It shouldn't matter if the hyperlink is underlined or not for the placement of the WCAG icon.

**Comment by JessicaFrank** [comment]
Fixed with code push scheduled for 5/4/2021
