### ISSUE TITLE
Duplicate entry in ckeditor textarea for legalnav resources

### ISSUE THREAD

**Issue by AnubhavDhingra** [CCALI/a2jauthor#171]
In the ckeditor the selected resource from the Legal Nav API's is displayed twice before saving the template.
The fix would be in the `a2j/deps` repository.
Potential Solution could be to have an if statement in the `a2j-legal-nav-resource.stache` to check for text being edited.
Important that this should not affect the display on saving the template.

**Comment by ghost** [comment]
Fixed with the Legal-Nav updates #168
