### ISSUE TITLE
editing richtext element changes legalnav guid to name instead of link

### ISSUE THREAD

**Issue by tobiasnteireho** [CCALI/a2jauthor#176]
There is a bug with the legalnav update where  if you edit the rich text element after a save/close and then save/close , the guid will change from the link to the name. This happens in chrome but not firefox. This change is reflected in the tempates.json. On firefox, the link _does_ disappear but the guid does not change.

related to #168

**Comment by tobiasnteireho** [comment]
how to reproduce 
![a2jauthor-legalnav-bug](https://user-images.githubusercontent.com/23437466/116721030-7c4ab900-a9a2-11eb-8766-7241fb92268c.gif)

**Comment by ghost** [comment]
Fixed with #168
