### ISSUE TITLE
Feature Request: Remove unused Calculator space on Number fields

### ISSUE THREAD

**Issue by normon66** [CCALI/a2jauthor#191]
Even when the calculator option is not enabled for a Number field, vertical space is still allocated for it, meaning there can be a huge amount of white space on a screen with numerous Number fields. 

This layout occurs frequently on fee waiver interviews. I have worked on a few that have 7 or 8 Number fields on a single screen, so the result would be that the user would have to scroll or swipe to see all of the fields, increasing the likelihood that they could miss one.

One solution would be to remove the white space if the calculator is not enabled, or the calculator could be moved inline with the field itself. 

![image](https://user-images.githubusercontent.com/32527754/122245568-11d2d700-ce83-11eb-8948-3c53befd5bd6.png)

**Comment by janebitovi** [comment]
<img src="https://user-images.githubusercontent.com/92131113/174312992-ee611274-894e-4d94-996b-2a75be2f30ed.png" width="350px">

coming soon

**Comment by normon66** [comment]
Nice!!!
