### ISSUE TITLE
Date widget allows invalid date

### ISSUE THREAD

**Issue by normon66** [CCALI/a2jauthor#196]
I fat-fingered a date and entered 042021980 into a date field while testing an interview on LHI (viewer version _A2J 7.0.19-2021-02-16_), though it let me continue (first image). This resulted in a document generation error on LHI (second image).

![image](https://user-images.githubusercontent.com/32527754/123558664-b9d68300-d754-11eb-9592-2a8f01e4b774.png)

![image](https://user-images.githubusercontent.com/32527754/123558687-d96dab80-d754-11eb-985c-26b026abca27.png)

**Comment by normon66** [comment]
A user-reported issue arose where documents were not generating on LHI. When I used the answers to run the interview, I found that a similar issue had occurred (it let the user enter "10/11/985" - note the missing 1 in 1985)

![image](https://user-images.githubusercontent.com/32527754/124996338-00a26380-e006-11eb-817a-73b9807584c4.png)

**Comment by mitch-mitchel** [comment]
tested both edge cases above in current author/viewer and they are handled correctly.  closing.
