### ISSUE TITLE
Mobile viewer: page following long page is out of view

### ISSUE THREAD

**Issue by normon66** [CCALI/a2jauthor#199]
While doing some analytics research for a partner, I noticed that an interview had significant drop rates after questions that asked for an address.

Being that over half of the users were on some type of iPhone, I tested it on my own iPhone. I found that on pages with a lot of text or fields (such as a page that collects a full address), you need to scroll down in order to tap and fill out all of the fields (first image below). Additionally, some number (e.g. Zip Code) and dropdown (e.g. State) fields cause a bit of a zooming effect, further focusing in on the bottom of the page.

Upon clicking the Continue button, the next page is also scrolled all the way down, and if it's a short page, it means that a lot of the page will be cut off (second image below), or in worse cases, no text or buttons are visible at all (the screen is just white space and the url - third image below).

When a page is loaded, it should default to the top of the page. I have no doubt that this is at least partially responsible for the drop rates. This may instead be an issue for LHI, in which case I am happy to bring it to their attention.

![image](https://user-images.githubusercontent.com/32527754/127064929-1225d7c2-8677-4e45-b92b-8094e4c01f4d.png)
- - - - - - - 
![image](https://user-images.githubusercontent.com/32527754/127064967-9cfd739e-e337-42b9-89b8-eb1e4924b9da.png)
- - - - - - - 
![image](https://user-images.githubusercontent.com/32527754/127065007-bbb84678-db15-4c99-b8af-fd45977844c9.png)

**Comment by JessicaFrank** [comment]
LHI is currently running an out of date viewer (5-11-2020 viewer as of 7/26/2021), so need to confirm this is also happening on current viewer, but sounds like the focus for the WCAG updates might be causing the issue. A somewhat similar issue of the continue button always being the "focus" when going to the next page happens on desktop too since WCAG tabbing improvements were added.

**Comment by janebitovi** [comment]
I can't reproduce this in the standalone viewer - hopefully this was fixed?

There is a problem in author preview that locks scrolling but it was done on purpose long ago so I have to ask why before moving forward with undoing that
