### ISSUE TITLE
Author using international keyboard with quotes throws logic error

### ISSUE THREAD

**Issue by JessicaFrank** [CCALI/a2jauthor#200]
Had an author report logic errors today and when I checked them it looked like his quotes were in italics. He said he was using an international keyboard because he writes in English and Spanish. Once he changed the quotes to standard ones, the error messages went away. 

Since we technically support interviews in other languages, we should allow for international keyboards. 

Does it require us to make changes to the logic parser to allow additional characters?

**Comment by tobiasnteireho** [comment]
Theoretically there could be countless quotation marks that is not easily detectable as a quotation mark. it might be reasonable to support at least these quotation marks https://www.cl.cam.ac.uk/~mgk25/ucs/quotes.html or some selection from https://en.wikipedia.org/wiki/Quotation_mark#Unicode_code_point_table. Can you please post the interview so we can see what code point was being used?

**Comment by janebitovi** [comment]
These quotes:
“”«»„“‟”❝❞〝〞〟＂
will all get replaced with " quotes now
![quotes-advanced-logic](https://user-images.githubusercontent.com/92131113/174084532-be3834c0-2a83-412b-9330-06b66fe6d186.gif)

```
goto 〝2-page〞
```
becomes
```
goto "2-page"
```
