### ISSUE TITLE
Auto assign step numbers

### ISSUE THREAD

**Issue by mitch-mitchel** [CCALI/a2jauthor#217]
Also, remove author ability to change those numbers. There really is no reason for an author to do a custom step number, and it causes bugs to have to handle that possibility. Auto number assignment is also a requirement for step merging in the Document component sharing TIG. Step numbers should still show below (just be uneditable)

![Screen Shot 2021-10-15 at 10 31 12 AM](https://user-images.githubusercontent.com/11528248/137514206-e0b4d06b-0c00-4d43-853b-9d911118d6dd.png)

@JessicaFrank we should still allow authors to re-order their steps, and just update the numbers based on the step positions right?

**Comment by JessicaFrank** [comment]
@mikemitchel yes. What about the up/down arrow that we have in the DAT Text templates, instead of the drag feature we have here.

**Comment by mitch-mitchel** [comment]
👍
