### ISSUE TITLE
Communicate “special container” via more than just styles

### ISSUE THREAD

**Issue by chasenlehara** [CCALI/a2jauthor#228]
As a screen reader user, I want special containers to be available in text, so that I can perceive them.

Currently, special containers in the preview document are only perceivable through visual styles. They should also be available in the text a screen reader announces to users.

**Comment by chasenlehara** [comment]
@JessicaFrank Question for you: how is the “special container” formatting used by authors? Right now it’s a styled `<div>` with a gray background and dark gray border; is there any semantic meaning that can be conveyed, or is it really just a stylistic choice when putting the document together?

**Comment by JessicaFrank** [comment]
@chasenlehara I don't understand what you mean by the 'special container'. What is that?

**Comment by chasenlehara** [comment]
Here’s what special container looks like in the styles list and when rendered in the document:

<img width="165" alt="Special container in the dropdown" src="https://user-images.githubusercontent.com/10070176/144648695-b05f634d-b7c5-4e07-92ce-3174ee84a82a.png">

<img width="723" alt="Rendered special container" src="https://user-images.githubusercontent.com/10070176/144648617-0d2be282-f4fa-4305-b1b6-99bf221f28f1.png">

**Comment by JessicaFrank** [comment]
Ok, yeah, I don't think that is used by authors. It may be, as I'm not familiar with all the templates our authors have made. But I don't teach new authors to use that special container.

**Comment by chasenlehara** [comment]
I’m going to close this as won’t fix—no harm if authors are using this for styling, as long as it isn’t intended to communicate any meaning. Alternatively, we could remove that option if it isn’t being used.
