### ISSUE TITLE
QA on Merge Tool

### ISSUE THREAD

**Issue by JessicaFrank** [CCALI/a2jauthor#242]
- [x] Need a back button at point of being inside the clone and selecting what to merge. 
- [x] Buttons should be at the top of the screen, not the bottom. Ex. Cancel; Choose a different starting point Or Merge Selected Or Safe Merge Selected. With a longer list of interviews (like mine that has hundreds), or a long interview with lots of components, the buttons get lost at the very end. 
- [x] What's the difference between merge selected and safe merge selected?
- [x] Need a way to name the interview when you create this new cloned interview. I couldn't find my merged interview once I saved it. 

I'll make a new part to this ticket as I continue to QA @janebitovi

**Comment by janebitovi** [comment]
Back button is at the bottom on the right

### When target is selected and source is not:
---
![image](https://user-images.githubusercontent.com/92131113/145879808-031206ab-2f2a-481c-9c34-6b452841aadb.png)

---
---

### When target and source are selected:
---
![image](https://user-images.githubusercontent.com/92131113/145879993-6b468f7b-e3f1-49fb-8bfb-516ac838add7.png)

This is what you're looking for in the first item, right?

**Comment by janebitovi** [comment]
- [x] Back button for each step (verified they all exist and work; no change, let's hop on a call if I'm missing something!)
- [x] Moved all buttons to the top, renamed "Cancel Without Saving" to "Exit Without Saving" to distinguish it from the other cancel buttons.
- [x] New: Refresh the interview list after saving
- [x] Interview title field added
  ![image](https://user-images.githubusercontent.com/92131113/146020580-5a407b31-5ff6-4f20-8989-ebb8b8067504.png)

- [x] Here's the difference between the buttons:

Merge button: Overwriting Merge
 1) var conflicts overwrite (name/etc)
 2) step conflicts overwrite (name/etc)
 3) new steps must be manipulated so the number/index doesn't leave a gap (merging step 3 into a guide with only step 1 puts the step 3 content into a new step 2)
 4) page name conflicts overwrite the page

Safe Merge button: Non-Overwriting Merge
 1) var conflicts create a new var with 'zzz' prefix
 2) steps are not copied over, instead a single new step is added and all pages go there
 3) page name conflicts create a new page with 'zzz' prefix

**Comment by janebitovi** [comment]
Hey @JessicaFrank this is complete (and on staging right now) but I imagine we'll want to show those ^ descriptions of merge vs safe-merge somewhere in the tool?
Thoughts?

**Comment by JessicaFrank** [comment]
@mikemitchel adding additional QA to version on hydra (4/13/22 version)

- [x] blank GI (the one to be merged into) doesn't come with 4 default pages that a standard blank GI comes with. I think this will create confusion for authors when they expect a normal blank GI and don't get that. Missing Step 0 Q 1-3 and Step 1 Q1
- [x] Step 1 here should say "Clone an existing interview or pick a blank interview for your starting point" 
![image](https://user-images.githubusercontent.com/7662028/164043513-6ac8b9cb-0f44-455d-9ec9-8df0f12bfbf9.png)

- [x] "Create a new Merged Interview" should be "Create a new merged interview" or "Create a New Merged A2J Guided  Interview"

**Comment by JessicaFrank** [comment]
- [x] Can the merge interview section be broken up into it's own header, so it's:

Create a new interview
Create a merged interview (maybe "Merge interview components" -- idk about the title, it needs work)
Edit on of my interviews

Something about "pick parts from existing interviews" doesn't sit right

![image](https://user-images.githubusercontent.com/7662028/164042748-dfe7eaa7-18c8-462c-881f-8e5b9d3b3efc.png)

**Comment by mitch-mitchel** [comment]
- [x] read media files
- [x] read template files
- [x] need guide root url in order to grab media and template assets
- [x] create checkable lists from the above file names/groups
- [ ] allow import of the above files the same as pages/steps
- [ ] allow safe import of the above files the same as pages/steps
- [ ] auto import any media file if an imported page is using it 
- [ ] auto import associated pdf base layer if pdf template.json file is imported (example template2.json and template2.pdf)
- [ ] files will need to be saved after the merged interview is created as we need a dest folder to place them in, which is only created on new merge guide save
- [ ] prevent nav away until merge is resolved, or preserve merge state upon return?
- [ ] if time is short, template and media files can be 'always a safe' merge, no overwrites
