### ISSUE TITLE
Advanced Navigation: page that will be skipped is shown as preview

### ISSUE THREAD

**Issue by normon66** [CCALI/a2jauthor#245]
The Navigation Panel intuitively shows the next few pages (up until a button choice can be made, it seems). This is nifty functionality, but can also 'preview' a page that is going to be skipped via BEFORE logic. 

For example, the page starting in _This tool can put "/s/"..._ (first image below) will actually be skipped in BEFORE logic (second image) and will go right to the _Congratulations..._ page (third image).
I would not expect the Navigation to actually determine logic ahead of time, but perhaps any page that contains a "GOTO" in the BEFORE logic should not ever be previewed in the Navigation Panel, just in case it will be skipped.

![image](https://user-images.githubusercontent.com/32527754/146050743-fcf74048-ca2d-40b7-b9c3-a743d5b4d634.png)

![image](https://user-images.githubusercontent.com/32527754/146051294-f7b440f1-b1c6-41f8-9eca-e1b5d546ad02.png)

![image](https://user-images.githubusercontent.com/32527754/146050963-5c7ab179-8c73-4806-8721-71f924a558b6.png)

**Comment by normon66** [comment]
I use a lot of logic-only pages to either begin a Step or to end a Step (a catch-and-release for multiple paths). I have a feeling that this sort of thing would be showing up on a lot of the tools that I have developed. 

![image](https://user-images.githubusercontent.com/32527754/146052533-8a4d35b9-cc01-45e4-93a4-9fdc261ecf91.png)

**Comment by janebitovi** [comment]
That page _should_ be excluded from the FuturePages because it has the before logic, I'll take a look, ty!
