### ISSUE TITLE
Choose your avatar question can't be skipped - problem with mobile + desktop

### ISSUE THREAD

**Issue by JessicaFrank** [CCALI/a2jauthor#248]
Testing mobile version of advanced nav code - get to the choose your avatar question. It says "User Avatar selection not supported in Mobile Viewer" which is fine, but I can't actually move on. Hitting continue does nothing. 

So I opened the interview in desktop and tried skipping answering the avatar question by not selecting an avatar and hitting "continue". Interview hangs up and I can't move on. Continue button stays highlighted like it is selected, but doesn't go anywhere.  No errors in the console. I am able to move on in the interview if I then go back and pick an avatar. 

Nothing on this page indicates it's required (no * or "required"), but I can't move on until I pick an avatar and I can't pick an avatar at all in mobile view.

**Comment by janebitovi** [comment]
I've ran through a handful of different scenarios using a new "blank" interview and again through the one you provided on slack and haven't been able to reproduce the error:
![avatarmobile](https://user-images.githubusercontent.com/92131113/146393850-384c80ab-7932-4447-a687-e79afb66932c.gif)

@JessicaFrank want to pair up and screenshare?

**Comment by JessicaFrank** [comment]
Can't replicate now. So closing.
