### ISSUE TITLE
Need to add Graphic Alt-Text and Video Transcript to Full Report

### ISSUE THREAD

**Issue by JessicaFrank** [CCALI/a2jauthor#25]
Added new fields to the Learn More info section of the questions. Need to add these to the Full Report. May need to add to text report as well -- assuming accessibility applies to other languages as well. 

- [ ] Graphic Alt-Text

- [ ] Video Transcript

- [ ] Media label

- [ ] Change "Help" to "Response"

![image](https://user-images.githubusercontent.com/7662028/85149423-e3420200-b216-11ea-80a5-3a48123a1341.png)

**Comment by janebitovi** [comment]
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/92131113/156047986-8e286c92-146a-4dda-84b7-a5accaec361d.png">
