### ISSUE TITLE
Advanced Navigation: cannot navigate to previous loop iteration

### ISSUE THREAD

**Issue by normon66** [CCALI/a2jauthor#252]
If I am on the second iteration of a loop and I try to use the Navigation Panel to go back to a question in the _first_ loop, I am taken to the corresponding question in the _second_ loop (the counter is still = 2).

This was likely done intentionally to prevent the counter from getting screwed up. However, if a user does not see that they are in the second loop and thinks that they actually _did_ jump to the first loop, they could easily enter the wrong information. 

Is there a way to revive [A2J Navigation TF] so that an author can just completely disable navigation during loops, or any other time they see fit?

**Comment by janebitovi** [comment]
Can you provide an example to recreate this? You should be able to jump anywhere at any time - all of my loop tests allow it so it's probably an author error or an oversight about *how* an author might be setting up their loops

Navigation won't be disabled during loops

**Comment by normon66** [comment]
@janebitovi - a sample interview is attached. 

- Start the Preview at page _1.1-Instructions (PPO Domestic)_ in Step 4. 
- Go through and enter information about a first incident ("incident 1", "details 1", etc)
- When asked if there are more incidents, say Yes
- Go through and enter information about a second incident ("incident 2", "details 2", etc)
- Navigate back to a question in the first loop (Step 4 Q6, in the below gif, which should go back to the page asking for the details of the first incident)
- Both the data on the page ("details 2") and the Navigation Panel (Step 4, Q14) are on the second loop.

![a2j issue 252](https://user-images.githubusercontent.com/32527754/146805460-c6a5bee9-3fa8-41d0-af53-6bf47d75dc4c.gif)

[MLHP - Petition for Personal Protection Order (1).zip](https://github.com/CCALI/a2jauthor/files/7746888/MLHP.-.Petition.for.Personal.Protection.Order.1.zip)

**Comment by janebitovi** [comment]
Fixed, same underlying issue as #254 
![loopjumpfix2](https://user-images.githubusercontent.com/92131113/146935621-d633888d-f73c-4505-a7d7-ab9802f21460.gif)
Selecting an existing visited page was causing the page route setter listeners to fire too which in some cases jumps to a different existing page based on loop variables global state
