### ISSUE TITLE
Bug with Back navigation

### ISSUE THREAD

**Issue by normon66** [CCALI/a2jauthor#253]
The Back navigation does not always take you to the previous page. This appears to happen any time said _previous page_ already appeared in the page history stack.

A sample interview is attached. Once you get to question 3, you can either go to 3.1, 3.2, or 4.
   ![image](https://user-images.githubusercontent.com/32527754/146417639-946cf58f-a00a-4cf1-bdaf-fd0031021b74.png)

First time through: go to question 3.1. From 3.1, clicking **Back** goes to question 3, as expected.
   ![image](https://user-images.githubusercontent.com/32527754/146417409-c4e29776-6842-4c8c-b03a-375a915dd692.png)

Second time through: Now back at question 3, go to question 3.2 this time.
   ![image](https://user-images.githubusercontent.com/32527754/146419867-86add04b-6299-4c71-acd9-110639a47c3e.png)

From 3.2, clicking **Back** _should_ take you to question 3, but instead, it goes to question 3.1.
   ![image](https://user-images.githubusercontent.com/32527754/146417985-9c49cc37-e51f-4580-bfb4-c39f4edb61c8.png)

When we went "back" to question 3, it didn't get re-added to the history. I created a ticket for this bug some time ago (it has existed for a long time), but cannot find it now. Perhaps it was in another repo (they seem to have changed a couple times)? 

[A2J Test Back-Next Navigation.zip](https://github.com/CCALI/a2jauthor/files/7729272/A2J.Test.Back-Next.Navigation.zip)

**Comment by janebitovi** [comment]
Using the provided guide, this works as you were expecting:
![backbranching](https://user-images.githubusercontent.com/92131113/146578305-ad20b653-9de8-4033-9281-763a8a09695d.gif)

Have I overlooked something in the instructions that would cause the break?

**Comment by JessicaFrank** [comment]
I'm getting the same results as Jane. The only way I get from 3.2 to 3.1 is if I follow the 3.1 button to 3.2. Otherwise, I always go back to 3 from either 3.1 or 3.2

![image](https://user-images.githubusercontent.com/7662028/146586308-64edf903-74ed-4b78-b2c1-b5042ebd3ba4.png)

**Comment by normon66** [comment]
Perhaps it's browser-specific (I tested on Chrome 96.0.4664.110). I can
check other browsers on Monday, possibly over the weekend

**Comment by normon66** [comment]
@janebitovi @JessicaFrank 
Please pardon the mixup, but this was in the production author, version _A2J 7.0.5-2021-05-04_. It does not happen in staging version _A2J 7.0-2021-08-11_, so that bug must have actually been fixed when implementing the advanced navigation feature!

**Comment by janebitovi** [comment]
No worries at all!
