### ISSUE TITLE
Advanced Navigation: navigating to previous loop entry can create 'rogue' page

### ISSUE THREAD

**Issue by normon66** [CCALI/a2jauthor#254]
If you are on a 2nd iteration of a loop and try to navigate back to a specific page that was asked during the first loop but _not_ the second loop, that page appears, but for the second loop (since the counter is still 2)

Sample interview is attached. 

- On the first time through the loop, answer **Yes** to each question, which will take you to a child question to enter more information. Those "child" pages will be added to the Navigation Panel
- On the second time through the loop, answer **No** to each question; the child pages are not shown.
- At the end of the second loop, navigate to one of the "child" pages. These were only answered in the first loop, but it will take you to the loop 2 instance (which was not and should not be asked)

Related to #252
[Advanced Navigation loop test 1.zip](https://github.com/CCALI/a2jauthor/files/7729649/Advanced.Navigation.loop.test.1.zip)

**Comment by janebitovi** [comment]
fixed
![](https://user-images.githubusercontent.com/92131113/146934127-de264d45-994f-4d3c-acfd-d2b5d187f57e.gif)
