### ISSUE TITLE
Minor: Less contrast in field borders

### ISSUE THREAD

**Issue by normon66** [CCALI/a2jauthor#259]
In the current staging environment (v _A2J 7.0-2021-08-11_), the field border lines were darkened substantially. I find the increased contrast to be a little hard on the eyes - can this be lightened a bit?

![image](https://user-images.githubusercontent.com/32527754/146802230-e284addf-12de-4115-9a4e-33e7a3b37f03.png)

![image](https://user-images.githubusercontent.com/32527754/146803043-1b0ab9af-ddf0-4de5-869f-2ebcb9998d6f.png)

![image](https://user-images.githubusercontent.com/32527754/146803077-d5befd84-c8c9-4d90-961b-d5a15a8d58fd.png)

**Comment by janebitovi** [comment]
Hey @normon66 ,

These borders needed to be darker for a11y compliance: [A11y Adjacent Colors](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html#:~:text=adjacent%20to%20white.-,Adjacent%20colors,For%20user%20interface%20components,-%27adjacent%20colors%27%20means)

If this higher contrast is something you don't grow accustom to and making them lighter again is something you continue wanting, we can potentially figure out something to help long term like user styles, other settings, etc.

Sound fair? Is it alright by you if I close this for now and you can circle back/re-open if it continues to be a concern down the road?

**Comment by normon66** [comment]
Gotcha - I figured it might have been related to some kind of compliance or
standard. I'll get used to it (even if I don't love it). Thanks for the
info!
