### ISSUE TITLE
Clone on Pages tab doesn't clone number of buttons in question

### ISSUE THREAD

**Issue by JessicaFrank** [CCALI/a2jauthor#26]
When using Clone button in Pages tab to create a duplicate copy of a question, it clones the page name (and appends a "2"/"3", etc) to the clone to differentiate it for the question naming purposes. 

It also clones the fields and the variables associated with those fields. Including repeat status. 

Does not clone buttons. So if author wants to clone a question with 3 buttons, in the clone only one button is there. 

Should clone everything the author adds to the questions- fields, learn mores, pop up links, and buttons. Probably logic too.

**Comment by ghost** [comment]
This seems to be working fine on production. @JessicaFrank could you verify this please.

**Comment by JessicaFrank** [comment]
@AnubhavDhingra confirmed that it's working as expected (clones multiple buttons) and closing ticket.
