### ISSUE TITLE
Multiple Choice options missing from debug panel script display

### ISSUE THREAD

**Issue by JessicaFrank** [CCALI/a2jauthor#276]
Display of answers being completed in the script portion of the debug panel is showing only multiple choice variables as "blank" even though they are answered. 

![image](https://user-images.githubusercontent.com/7662028/148455859-b0049874-9aec-46dc-8a78-31522f904625.png)

The answer is being stored in the answer file, but it's not displaying to the authors as it's answered.

**Comment by janebitovi** [comment]
was related to https://github.com/CCALI/CAJA/issues/2432
