### ISSUE TITLE
Reorder drag icon doesn't actually do anything for fields

### ISSUE THREAD

**Issue by JessicaFrank** [CCALI/a2jauthor#297]
Icon intended to allow dragging and reordering of fields doesn't actually reorder them. We should remove that option. Drag and drop is problematic in other areas (like the DAT), so it should be removed throughout. 

Possibly re-instate a new reordering system that adjusts the order of the fields without requiring drag and drop. 

Also present in the buttons section.

**Comment by janebitovi** [comment]
Replaced with the up/down arrows we did previously on the buttons tab. Will go live with other changes in #321 
<img width="168" alt="image" src="https://user-images.githubusercontent.com/92131113/174094310-a4a2fe29-211e-4ac2-ac2a-a8a4cfdfe349.png">
