### ISSUE TITLE
Text indent is being stripped out of DAT rich text elements (ck-editor)

### ISSUE THREAD

**Issue by JessicaFrank** [CCALI/a2jauthor#305]
Author attempting to use 'text-indent' in a rich text element in the DAT Text Templates to do a first word indent in a paragraph. Editor is stripping it out. This happens for both <p> and <div> elements.

Work around is to use 'margin-left', but that indents the entire paragraph, not just the first word of a paragraph of unknown text length. 

*issue submitted by LSLA

**Comment by JessicaFrank** [comment]
Author suggestion: I imagine that changing “config.js” to configure extraAllowedContent to allow the style might work. I’m seeing https://stackoverflow.com/questions/15659390/ckeditor-automatically-strips-classes-from-div/15659962#15659962 as a suggestion for CKEditor 4.1+.

**Comment by tobiasnteireho** [comment]
altered `config.js` and rebuilt but settings did not take effect. Need more investigation

**Comment by tobiasnteireho** [comment]
above is in this commit -> https://github.com/CCALI/a2jauthor/commit/e8f24b204d6da1b0dd4e373594374160145a7b6c

**Comment by tobiasnteireho** [comment]
would it be sufficient in the meantime to just use spaces at the beginning of he paragraph? ckeditor keeps them as non-breaking spaces

**Comment by tobiasnteireho** [comment]
fixed by https://github.com/CCALI/a2jauthor/pull/307
