### ISSUE TITLE
Allow proper preview of Popup pages

### ISSUE THREAD

**Issue by mitch-mitchel** [CCALI/a2jauthor#306]
Popup pages are really  modals as far as display for their content, and should launch a modal to preview them, possibly setting some default page (the intro page?) as their background.  The old method would just preview them as Question text, but now that they have all the media options, the question text bubble isn't a proper preview. 

Another option is to use the author modal to display a Popup preview directly, without launching the actual viewer since in this case the background behind the Popup doesn't really matter and can be fogged out. The <content /> tag of the Author modal would just be a stache copy of the Viewer modal.

@JessicaFrank feel free to opine here ...

**Comment by mitch-mitchel** [comment]
ps - current solution is Preview button is disabled for Popup pages and they only preview when linked in a normal page and launched from the link in the viewer.

**Comment by JessicaFrank** [comment]
I prefer the option of previewing a pop up within the viewer, with a default question behind it. It feels more authentic to an actual "preview" of what the pop up will look like to an end user. 

However, expediency and resource conservation are most important for this deliverable, so I'm fine with whichever option (including just hiding Preview option from pop up editor) is easiest/fastest.

**Comment by JessicaFrank** [comment]
Graying out the preview button for pop ups is the current state.

**Comment by janebitovi** [comment]
![preview-popup](https://user-images.githubusercontent.com/92131113/174343430-529272eb-3deb-4081-baef-63bb46e5d587.gif)

if 'currentPage' in viewer is set to a popup (only happens from author preview), show a message in the avatar's chat bubble that links to the popup
