### ISSUE TITLE
Calculator button unresponsive

### ISSUE THREAD

**Issue by normon66** [CCALI/a2jauthor#329]
In staging v _A2J 10.0.0-0-2022-06-22_, nothing happens when you click the calculator button. No messages are shown in the developer console. Tested on Chrome 102.0.5005.115.

![image](https://user-images.githubusercontent.com/32527754/175568777-ef264bd5-7dc3-4c85-8dbe-3b3c48d904d4.png)

**Comment by janebitovi** [comment]
this is because there is no label - problem exists on production too - also happens with calendar button
will fix before push, thank you!
