### ISSUE TITLE
Auto-suggest GOTO page name - account for indents

### ISSUE THREAD

**Issue by normon66** [CCALI/a2jauthor#333]
If a GOTO statement is indented with a space, the auto-suggest does not activate:
![image](https://user-images.githubusercontent.com/32527754/175607742-8687c1c0-f657-4d3d-b3c0-3b8a17823d21.png)

The auto-suggest for the SET statement, however, _does_ work if the statement is indented:
![image](https://user-images.githubusercontent.com/32527754/175607855-a1c9783f-8ab6-4184-9dc4-45abb317ed5f.png)

**Comment by janebitovi** [comment]
validation check doesn't run either - will fix, thank you!
