### ISSUE TITLE
Auto-suggest variable and media lists do not go away when focus is lost

### ISSUE THREAD

**Issue by normon66** [CCALI/a2jauthor#334]
When you click into a field where the name of a variable would go, the auto-suggest list of variables automatically shows up. This is all good, but when you click out of that field, the list remains visible. Ideally, the list would go away once the focus changes (i.e. another field is selected, or that field is tabbed out of). 
![image](https://user-images.githubusercontent.com/32527754/175608541-c2382fc0-12b0-4f58-9cd1-c5a8ffc323b9.png)

This same thing goes for media fields. Here, the 'focus' is on the Video Transcript field, yet all three of the media lists are still showing since I clicked in them previously.
![image](https://user-images.githubusercontent.com/32527754/175608394-5a067526-342f-4ce8-b4e2-127856a85794.png)

**Comment by janebitovi** [comment]
I've linked all the new dropdowns so only one will show at a time, and it will close if you focus on another field even if it doesn't have a new dropdown itself
