### ISSUE TITLE
Tabbed layout: combine tabs?

### ISSUE THREAD

**Issue by normon66** [CCALI/a2jauthor#338]
I think I would prefer to have the Page Info and Question Info tabs consolidated. These both contain fields that will always be filled on out every single page, so it would be a little easier and a little faster to have them all in one place. 

![image](https://user-images.githubusercontent.com/32527754/175644040-e83e2f42-6458-45e2-b7cb-3c18b9ed4196.png)

**Comment by janebitovi** [comment]
This is a great observation imo, will ask Jessica for approval and see if we can get it in before launch
Thank you!

**Comment by janebitovi** [comment]
:)

<img width="912" alt="image" src="https://user-images.githubusercontent.com/92131113/175650533-ef346294-efc4-4714-a75c-cbbba8519a03.png">
