### ISSUE TITLE
KUDOS to the entire A2J team

### ISSUE THREAD

**Issue by normon66** [CCALI/a2jauthor#339]
While designing a new interview to test the Merge Tool, I stumbled across a number of the recent updates, which I only later noticed in an email from Jessica. 
A2J Author has come such a long way in these last few years, and I'll be the first to admit that it has caused a bit of swearing over the years. :) 
I wanted to give some props where everyone would be sure see it, and to personally thank you for dedicating thought, design, time, energy, and funds on these author-centric updates, which will greatly improve the authoring experience. I do apologize if this is an inappropriate venue, but I thank you, regardless.

- I think the tabbed layout is going to be a big add. After just using it for a short while to create the test interview, I found myself struggling to find things when I went back to production Author.
![image](https://user-images.githubusercontent.com/32527754/175645392-9ec76b2c-5d75-4d1a-ad70-6271e42eeefa.png)

- I love the new field up/down buttons! The drag and drop version worked, but was sometimes clumsy to use.
![image](https://user-images.githubusercontent.com/32527754/175644467-418f9f8c-f9c5-4e71-b58f-df3062ee9c7c.png)

- I REALLY love being able to add variables on the fly, rather than having to close out of the question editor, go back to the Variables tab, create the variable, then go hunt down and select the question again.
- It is also nice to be able to search for other media files that have already been uploaded. This is a time-saver and will help prevent duplicate files. 
![image](https://user-images.githubusercontent.com/32527754/175644591-f9f7fd34-136c-4047-b6bb-18fa3440bffe.png)

- Holy smokes! Auto-suggest / intellisense in the LOGIC areas!!??!?! WOW - great work!
![image](https://user-images.githubusercontent.com/32527754/175644636-7eea786e-40d2-4a8a-8dac-f81f6fd7a15b.png)

- Being able to edit the NEXT page?! Great idea!
![image](https://user-images.githubusercontent.com/32527754/175644667-aa058f70-2f38-4760-9711-cf7d064f3376.png)

**Comment by tobiasnteireho** [comment]
dankeschön, Brett!
