### ISSUE TITLE
'Intro / Step 0' checkbox causing incorrect step selection in page editor

### ISSUE THREAD

**Issue by normon66** [CCALI/a2jauthor#342]
The newest viewer has the new "Start with an Intro Step (Step 0)" checkbox.
![image](https://user-images.githubusercontent.com/32527754/176745333-d9457523-4e6e-4502-86c5-ac95c29491cb.png)

In my existing interview (guide.xml attached), I had already just started with Step 1, so the box understandably was not checked:
![image](https://user-images.githubusercontent.com/32527754/176746405-e762f0e2-7d21-4e62-a616-a1a79407985b.png)

However, upon editing a page, the wrong Step is now selected in in the dropdown since, behind the scenes, these steps were still 0-based.

Take page "1-Introduction - ELDER ONLY", which should be on Step 1. Introduction
![image](https://user-images.githubusercontent.com/32527754/176747227-b2c724b1-3308-4076-ad9d-eee4a3de98da.png)
![image](https://user-images.githubusercontent.com/32527754/176746975-a822c40e-5055-4863-b7a7-b4f3e1797ff7.png)

Or the page "1-P Address", which should be on Step 2. The Protected Party
![image](https://user-images.githubusercontent.com/32527754/176747392-991fee74-32b3-4c26-9ba0-0a872d6f74d1.png)
![image](https://user-images.githubusercontent.com/32527754/176747504-07e92190-114f-4b75-8b26-96851b81cee6.png)
[IJB Guide.xml.txt](https://github.com/CCALI/a2jauthor/files/9022295/IJB.Guide.xml.txt)

I tested this out on an interview that DID have an actual Step 0, and it appears to work correctly.

**Comment by JessicaFrank** [comment]
This is still present in staging, as far as I can tell. 
Steps I used for testing - created an interview in production (with old code) that was set to start on Step 1. There's no step 0 according to the steps tab. 

Opened that GI in staging with new code. Shows on steps tab that there's no step 0 and interview starts on step 1. 
![image](https://user-images.githubusercontent.com/7662028/183687488-ab0116c7-7f63-4933-9580-5ea2cb390974.png)

However, opening xml still shows step 0 associated with name of the page. 

Ex. Page "1-Introduction" says Step 0 in xml, but shows as Step 1 in pages tab and steps tab.
![image](https://user-images.githubusercontent.com/7662028/183687675-2f5b155b-9ddd-4ab8-a3bf-af36f6c172e3.png)
