### ISSUE TITLE
Mike's A2J punch list

### ISSUE THREAD

**Issue by mitch-mitchel** [CCALI/a2jauthor#346]
Review, update and add to the docs as needed to make sure they represent the current state of the Repos. 

- [ ] Diagram of how repos work together - diagram how a2jdeps are shared/used 
- [x] Complete A11y final review/audit
- [x] Release steps, including npm releases and deps tree, build process
- [x] Identify where the weird stuff lives - legacy jquery app code & global events and listeners that connect legacy and canjs
- [x] Get john and tobias invites to the community slack
- [x] Resolve develop branch build issue
- [x] Check if nested var search/dictionary works in current production

**Comment by JessicaFrank** [comment]
Any common tricks you use when debugging with me would be helpful legacy knowledge. I'm not thinking of any right off the top of my head, but you're a quick debugger, so this can go into the "where weird stuff lives" pile.
