### ISSUE TITLE
Third level of var picker on templates doesn't recognize default variables

### ISSUE THREAD

**Issue by JessicaFrank** [CCALI/a2jauthor#347]
Text template, IF/Else element (or legal nav if/else element), then add a repeat loop element inside that IF/Else

Variables that were created by the author display as expected and can be searched for using the var picker. Variables that are in an interview by default (like Client first name TE) show as "no match" while you're trying to insert them in a repeat loop element "list" or "table" 

If you type it in anyway and hit save &close, the variable looks like it is a variable inserted correctly. This is true for real variables and variables that aren't actually in the variable list at all (like if you misspell the variable name). 

If the variable is actually in the variable list and in the anx file, it assembles as expected, even though A2J Author said "no match" when inserting it. 

Sample interview with basic text template to try. 
[Vars third level deep in a template test GI (July 2022).zip](https://github.com/CCALI/a2jauthor/files/9056406/Vars.third.level.deep.in.a.template.test.GI.July.2022.zip)

Answer file to use. (in a zipped folder b/c Github doesn't support anx files)
[answer - 2022-07-06T105407.350.zip](https://github.com/CCALI/a2jauthor/files/9056416/answer.-.2022-07-06T105407.350.zip)

**Comment by mitch-mitchel** [comment]
Repeat loops filter for variables of type 'repeating' and no default variables are of repeating type. Currently going to push this back to Author training, but we could update the 'no match' error message that shows to be 'no repeating variable match' when that filter is engaged. @JessicaFrank 

filtering happens here:
https://github.com/CCALI/a2jdeps/blob/772e65705d9f3be00277bd840f8b8d5b1f87cb2d/elements/variable-picker/variable-picker-vm.js#L107
