### ISSUE TITLE
Add source to CK editor in question design tab (like in Templates tab)

### ISSUE THREAD

**Issue by JessicaFrank** [CCALI/a2jauthor#361]
Author request:
''I have tried to edit the question 1-No in this interview a few times, but I cannot get p tags in.

There is no source in the interview WYSIWYG button in the pages/questions editor as there is in the template editor.

Could you please add this button?

I cannot tell what the tags are until I download the a2j author zip, create a new page on Legal Navigator and then attach and upload the zip file to this new page.

Royal pain – not your problem, but a source button on the page pages editor would make my job soooooooooooooooooooo much easier!"

**Comment by JessicaFrank** [comment]
Follow up to this initial request:

"I have not found a pattern or way to control if text is just plain text or enclosed in <p> tags in interviews.
I gather from A2J Author Viewer this is not an issue, but when an interview is embedded in another website the CSS will treat plain untagged text differently from text within <p> tags.
Also it seems that hitting Enter at the end of a link when editing in A2J author produces a <br /> tag
And Shift enter produces a <p> tag, maybe?
I am not sure if I have these straight or backwards, or we don’t have a consistent way to create either.
I am finding more and more that my text is not enclosed in tags – not sure if this is because I am pasting plain text in, pasting with Ctrl + Shft + V to avoid any Word garbage coming in – like <p class=”dir”>  - or typing directly into the interview.
I so wish we could view and edit xml – at least view as we used to be able to do  -
Anyhow, is this something your developers could just enable in the WYSIWYG editor for interviews – could we not just use the same settings for the editor for interview text as we use for editing templates?"

**Comment by tobiasnteireho** [comment]
Looking at the code it is not clear why the p tags are inconsistent. It is not obvious to me that there is a way to ensure that text is always enclosed in `p` tags without the source button.
