### ISSUE TITLE
Does this mean legalnav API is broken?

### ISSUE THREAD

**Issue by JessicaFrank** [CCALI/a2jauthor#379]
We have two calls to the LegalNav API built into the A2J DAT text templates for GUID resource lookups. During testing on another issue, I saw this error in the console. 

Does this mean the legalnav.org integration is broken? 

If yes, should we 1. reach out to LSC and/or 2. remove references to LegalNav from A2J DAT?

![image](https://user-images.githubusercontent.com/7662028/231485748-c3d61d8f-91e6-417a-b7db-96b3605ec57d.png)

**Comment by tobiasnteireho** [comment]
The whole legalnav.org website seems to be down. It 404s and the certificate is invalid.

**Comment by tobiasnteireho** [comment]
If legalnav doesn't exist anymore we should probably remove references to it.

**Comment by tobiasnteireho** [comment]
Unfixable without new functional endpoints. related to #385.
