### ISSUE TITLE
Editing field label causes extra <p> and bad page spacing

### ISSUE THREAD

**Issue by normon66** [CCALI/a2jauthor#95]
When a field is first created (or had been imported from A2J4), the label sits right above the field, and the optional (Required) label is on the same line.
However, if you edit the label, an extra <p> is inserted into the html via the edit box, causing a significant change in the vertical spacing via larger margins/padding, as well as bumping the (Required) label to the next line.
Aesthetically and from an ease-of-use perspective, the (Required) works better on the same line as the label itself. Additionally, for a page with more than just a couple of fields, this uses up way more screen space than is needed, which could be an issue for mobile or tablet users, some laptop users, or those who have larger text sizes for accessibility purposes.
It is possible (I do it all the time) to download the interview zip file, extract the guide.xml, perform a search and replace (which only works some of the time - other times you have to track them down one-by-one), replace the guide.xml in the zip file with the modified version, and reupload the entire zip to a2jauthor as a new interview. This can be rather time intensive, error-prone, bloats the content stored on the authoring server, and is likely beyond (and unknown) to a number of interview authors.

Verified in Chrome and Firefox, and has been an issue for at least a year.

![image](https://user-images.githubusercontent.com/32527754/99917616-9f27c180-2cce-11eb-9e16-87073dbb4b2b.png)

![image](https://user-images.githubusercontent.com/32527754/99917619-a51da280-2cce-11eb-9800-dfd9c53e5b23.png)

**Comment by janebitovi** [comment]
It will no longer add the P tag automatically for new edits. 

Existing P tags won't be removed. If it's already there, authors can clear the field and re-enter just the text.

Authors can press SHIFT+ENTER to continue using P tags like it was doing before if they wish.

**Comment by normon66** [comment]
This is still happening (or is happening again). After editing the labels of the two highlighted checkboxes in the image below, extra spacing appears. In the editor, a p is shown (second image) that explains this, which is also seen within the <label> of that field (third image, which also has an unedited field highlighted for comparison). 

Using A2J v _A2J 9.0.0-2022-03-24_

![image](https://user-images.githubusercontent.com/32527754/161351387-f14a0236-4bb4-4818-954f-12bff93a9e67.png)

![image](https://user-images.githubusercontent.com/32527754/161351521-2905841e-5c80-446e-8609-d3ebdeffd02d.png)

![image](https://user-images.githubusercontent.com/32527754/161351804-420d310a-2740-4f4a-8d4b-18e7d2e2d485.png)

**Comment by normon66** [comment]
White testing the new Merge Components functionality in staging version _A2J 10.0.0-0-2022-06-22_, I noticed that this appears to be fixed.
